ModelBinder/Models/EnclosurePart.cs
using System.ComponentModel.DataAnnotations;

namespace Models;

public class EnclosurePart
{
    [Key]
    public int Id { get; set; }

    public int PartId { get; set; }

    public int EnclosureId { get; set; }
    
    public string Tag { get; set; }

    public double Quantity { get; set; }

    public int PartOrderId { get; set; }
    
    public OrderDelivery Delivery { get; set; }   
}

ModelBinder/Models/ErrorViewModel.cs
namespace ModelBinder.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ModelBinder/Models/OrderDelivery.cs
public enum OrderDelivery
{
    ACS = 1,
    Client = 2,
    EndClient = 3,
    Subcontractor = 4,
}

ModelBinder/Controllers/BindController.cs
using Microsoft.AspNetCore.Mvc;
using ModelBinder.Data;
using Models;

namespace ModelBinder.Controllers
{
    public class BindController : Controller
    {
        private readonly ApplicationDbContext _context;

        //[BindProperty]
        //public List<EnclosurePart> EnclosureParts { get; set; }

        public BindController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _context.EnclosurePart.AsEnumerable().ToList();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(List<EnclosurePart> model)
        {
            foreach (var part in model)
            {
                var Existed_Emp = _context.EnclosurePart.Find(part.Id);
                Existed_Emp.Delivery = part.Delivery;
                Existed_Emp.EnclosureId = part.EnclosureId;
                Existed_Emp.Tag = part.Tag;
                Existed_Emp.Quantity = part.Quantity;
            }

            _context.SaveChanges();

            return View(model);
        }
    }
}

ModelBinder/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ModelBinder.Models;
using System.Diagnostics;

namespace ModelBinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ModelBinder/Views/Bind/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ModelBinder/Views/Bind/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Models
@model List<Models.EnclosurePart>

@{  
    ViewBag.Title = "Index";  
} 

<h2>Parts Table</h2>

@using (Html.BeginForm("Index", "Bind", FormMethod.Post, new List<EnclosurePart>()))
{
    @Html.AntiForgeryToken()
    @*<form method="post">*@
    <table class="table">
        <thead>
            <tr>
                <th>Delivery</th>
                <th>Enclosure Id</th>
                <th>Quantity</th>
                <th>Tag</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.Hidden("model[" + @i + "].PartId", Model[@i].PartId)
                        @Html.Hidden("model[" + @i + "].Id", Model[@i].Id)
                        @Html.Hidden("model[" + @i + "].PartOrderId", Model[@i].PartOrderId)
                        @Html.DropDownList("model[" + @i + "].Delivery",
                @Html.GetEnumSelectList<OrderDelivery>())
                        @*<select class="form-select" name="delivery" aria-label="Delivery" asp-items="@Html.GetEnumSelectList<OrderDelivery>()"></select>*@
                    </td>
                    <td>
                        @Html.TextBox("model[" + @i + "].EnclosureId",  
                Model[@i].EnclosureId)
                        @*<input type="text" name="enclosure" value="@item.EnclosureId" />*@
                    </td>
                    <td>
                        @Html.TextBox("model[" + @i + "].Quantity",  
                Model[@i].Quantity)
                        @*<input type="text" name="quantity" value="@item.Quantity" />*@
                    </td>
                    <td>
                        @Html.TextBox("model[" + @i + "].Tag",  
                Model[@i].Tag)
                        @*<input type="text" name="tag" value="@item.Tag" />*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
    @*</form>*@
}

ModelBinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ModelBinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelBinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ModelBinder.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModelBinder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ModelBinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>